name: corund
on:
  pull_request:
permissions:
  contents: read
  checks: write
  pull-requests: write
jobs:
  corund:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"
      - run: pip install pytest
      - uses: Grade-Inc/corund-action@v0.1.3
        with:
          test-command: python -m pytest
